import os
from dataclasses import dataclass


@dataclass(frozen=True)
class Settings:
    # APP_NAME must match this app's ECR repo / IAM role name / Postgres
    # database name / Route53 subdomain -- one name ties the whole platform
    # integration together, see docs/app-platform.md in nyc_pa_aws_gitops.
    app_name: str = os.environ.get("APP_NAME", "app")

    # SESSION_SECRET should come from SSM (/home-platform/<app>/session-secret)
    # once deployed -- the default here is only for local dev/tests, never
    # use it in production.
    session_secret: str = os.environ.get("SESSION_SECRET", "dev-insecure-secret-change-me")

    # Postgres (ADR-0016). POSTGRES_PASSWORD arrives via the platform's
    # deploy-time .env convention -- unset locally means db-dependent
    # features degrade gracefully instead of crashing (see app/db.py).
    postgres_host: str = os.environ.get("POSTGRES_HOST", "postgres")
    postgres_password: str | None = os.environ.get("POSTGRES_PASSWORD")
    # Full SQLAlchemy URL, overriding the two above. Unset in production;
    # tests set it to a SQLite file to run the migrations without Postgres.
    database_url: str | None = os.environ.get("DATABASE_URL")

    # gRPC server (ADR-0020): internal-only, port 9090 by convention.
    grpc_port: int = int(os.environ.get("GRPC_PORT", "9090"))

    # Authentik OIDC (ADR-0017, Pattern A). Both unset means auth routes
    # respond 501 instead of crashing -- lets this template run standalone
    # before an app is actually onboarded to Authentik.
    authentik_base_url: str = os.environ.get("AUTHENTIK_BASE_URL", "https://auth.billandjessie.com")
    authentik_client_id: str | None = os.environ.get("AUTHENTIK_CLIENT_ID")
    authentik_client_secret: str | None = os.environ.get("AUTHENTIK_CLIENT_SECRET")


    # Airflow job token (ADR-0031 in nyc_pa_aws_gitops): generated by the
    # platform at /home-platform/secmaster-svc/airflow-token and delivered by
    # the deploy. /jobs/* require it as a bearer token; unset means /jobs/*
    # answer 503 rather than run unauthenticated.
    airflow_token: str | None = os.environ.get("AIRFLOW_TOKEN")

    # Read-only token, accepted on the job API's GET endpoints (lookups), like
    # mkt-data's READ_TOKEN. Optional; the Airflow token works there too.
    read_token: str | None = os.environ.get("READ_TOKEN")

    # mkt-data's gRPC server, for its near-raw records (Treasury securities, phase 3).
    mkt_data_grpc: str = os.environ.get("MKT_DATA_GRPC", "mkt-data:9090")

    # calendar-svc's gRPC server, for the business days futures contracts are generated from (phase 4).
    calendar_svc_grpc: str = os.environ.get("CALENDAR_SVC_GRPC", "calendar-svc:9090")

    # OpenFIGI API key (SSM /home-platform/secmaster-svc/openfigi-api-key). Optional: without it the
    # FIGI job runs at OpenFIGI's keyless limits and does a few hundred CUSIPs a run.
    openfigi_api_key: str | None = os.environ.get("OPENFIGI_API_KEY")


settings = Settings()
